name: demopod
description: "A SolidPod Demonstrator."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  editable: ^2.0.0
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  rdflib: ^0.2.10
  solidpod:
    path: ..
  universal_io: ^2.2.2
  window_manager: ^0.3.7

dev_dependencies:
  # dart_code_metrics:
  #   git:
  #     url: https://github.com/anusii/dart-code-metrics.git
  #     ref: dev
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
