name: demopod
description: "A SolidPod Demonstrator."

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  editable: ^2.0.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  solidpod:
    path: ..
  universal_io: ^2.2.2
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  intl: ^0.19.0 # Eventually remove. Through solidpod, solid-auth depends on intl-0.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
