name: demopod
description: "A SolidPod Demonstrator."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  editable: ^2.0.0
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  intl: any
  rdflib: ^0.2.11
  #
  # In testing the package in the context of the github clone we get
  # the solidpod package from the parent folder. Otherwise if this is
  # a standalone copy of the example folder, then obtain solidpod
  # from the dart repository. (gjw 20250429)
  #
  # solidpod: ^0.7.0
  #
  solidpod:
    path: ..
  universal_io: ^2.2.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
