name: demopod
description: 'A SolidPod Demonstrator.'
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  editable: ^2.0.0
  file_picker: ^10.3.10
  flutter:
    sdk: flutter
  intl: any
  markdown_tooltip: ^0.0.10
  rdflib: ^0.2.12
  solidpod: ^0.11.0
  solidui: ^0.2.0
  universal_io: ^2.3.1
  window_manager: ^0.5.1

dependency_overrides:
  solidpod:
    path: ..
  solidui:
    git:
      url: https://github.com/anusii/solidui.git
      ref: tony/127_browserpod

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
