name: demopod
description: "A SolidPod Demonstrator."
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  editable: ^2.0.0
  file_picker: ^10.1.2
  flutter:
    sdk: flutter
  intl: any
  rdflib: ^0.2.12
  solidpod:
    path: ..
  solidui: ^0.0.22
  universal_io: ^2.3.1
  window_manager: ^0.5.1

dev_dependencies:
  flutter_lints: ^5.0.0

dependency_overrides:
  solidpod:
    path: ..

flutter:
  uses-material-design: true
  assets:
    - assets/images/
