# include: package:flutter_lints/flutter.yaml
include: package:ubuntu_lints/analysis_options.yaml
# include: package:solid_lints/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.mocks.dart"
    - "**/l10n/*.dart"

linter:
  rules:
    avoid_print: true
    directives_ordering: false # I prefer grouped directive ordering
    public_member_api_docs: true
