name: solidpod
description: A library to support easy access to data stored on Pods in Solid servers.
version: 0.6.3
homepage: https://github.com/anusii/solidpod

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  crypto: ^3.0.3
  encrypt: ^5.0.3
  fast_rsa: ^3.6.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  form_builder_validators: ^11.0.0
  http: ^1.2.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  loading_indicator: ^3.1.1
  package_info_plus: ^8.0.1
  path: ^1.9.0
  pointycastle: ^3.9.1
  rdflib: ^0.2.10
  solid_auth: ^0.1.22
  # solid_auth:
  #   path: ../solid-auth # Use a local path whilst solid auth is under development.
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: dev
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  # Not yet use solid-lints. It requires analyze 6.2.0 and
  # dart-code-metrics fails.
  # solid_lints: ^0.1.1
  lints: ^4.0.0
  ubuntu_lints: ^0.4.0

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependency_overrides:

flutter:
  assets:
    - assets/images/default_image.jpg
    - assets/images/default_logo.png
