name: solidpod
description: Support easy access to data stored on Solid Pod servers.
version: 0.5.6+5
homepage: https://github.com/anusii/solidpod

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.3
  encrypt: ^5.0.3
  fast_rsa: ^3.6.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.5
  form_builder_validators: ^9.1.0
  http: ^1.1.2
  intl: ^0.18.0
  jwt_decoder: ^2.0.1
  loading_indicator: ^3.1.1
  markdown_editor_plus: ^0.2.13
  package_info_plus: ^5.0.1
  rdflib: ^0.2.8
  solid_auth: ^0.1.16  # solid-auth can get refresh token since version 0.1.15
  solid_encrypt: ^0.1.10
  url_launcher: ^6.2.4

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: main
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # Not yet use solid-lints. It requires analyze 6.2.0 and
  # dart-code-metrics fails.
  # solid_lints: ^0.1.1
  ubuntu_lints: ^0.3.0

dependency_overrides:
  file: ^7.0.0
  intl: ^0.19.0  # solid-auth depends on intl-0.19.0

flutter:
  assets:
    - assets/images/default_image.jpg
    - assets/images/default_logo.png
