name: solidpod
description: A library to support easy access to data stored on Pods in Solid servers.
version: 0.6.4
homepage: https://github.com/anusii/solidpod

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  crypto: ^3.0.6
  encrypt: ^5.0.3
  fast_rsa: ^3.7.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.7.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  form_builder_validators: ^11.1.1
  http: ^1.3.0
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  loading_indicator: ^3.1.1
  package_info_plus: ^8.1.4
  path: ^1.9.0
  pointycastle: ^3.9.1
  rdflib: ^0.2.11
  solid_auth: ^0.1.22
  # solid_auth:
  #   path: ../solid-auth # Use a local path whilst solid auth is under development.
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.14
  custom_lint: ^0.7.1
  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: dev
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  # Not yet use solid-lints. It requires analyze 6.2.0 and
  # dart-code-metrics fails.
  # solid_lints: ^0.1.1
  lints: ^5.1.1
  ubuntu_lints: ^0.4.1

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependency_overrides:
  collection: ^1.19.0

flutter:
  assets:
    - assets/images/default_image.jpg
    - assets/images/default_logo.png
