name: solid
description: Support access to a Solid server for securing personal online data.
version: 0.3.0+6
homepage: https://github.com/anusii/solid

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  fast_rsa: ^3.6.1
  flutter:
    sdk: flutter
  http: ^1.1.2
  jwt_decoder: ^2.0.1
  loading_indicator: ^3.1.1
  package_info_plus: ^5.0.1
  solid_auth: ^0.1.13
  url_launcher: ^6.2.4

dev_dependencies:
  dart_code_metrics:
    git:
      url: https://github.com/anusii/dart-code-metrics.git
      ref: main
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  # Not yet use solid-lints. It requires analyze 6.2.0 and
  # dart-code-metrics fails.
  # solid_lints: ^0.1.1
  ubuntu_lints: ^0.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  # To add assets to your package, add an assets section, like this:

  assets:
    - assets/images/default_image.jpg
    - assets/images/default_logo.png
  #  - assets/images/default_logo.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
