/// Per-pair encryption key management for notifications.
///
/// Copyright (C) 2026, Software Innovation Institute, ANU.
///
/// Licensed under the MIT License (the "License").
///
/// License: https://choosealicense.com/licenses/mit/.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
///
/// Authors: Tony Chen

library;

import 'dart:convert';

import 'package:flutter/foundation.dart' show debugPrint;

import 'package:encrypter_plus/encrypter_plus.dart';
import 'package:pointycastle/asymmetric/api.dart';

import 'package:solidpod/src/solid/api/rest_api.dart';
import 'package:solidpod/src/solid/constants/common.dart';
import 'package:solidpod/src/solid/utils/data_encryption.dart';
import 'package:solidpod/src/solid/utils/get_url_helper.dart';
import 'package:solidpod/src/solid/utils/key_helper.dart'
    show RecipientPubKey, genRandIV;
import 'package:solidpod/src/solid/utils/key_manager.dart';
import 'package:solidpod/src/solid/utils/notification_pair_id.dart';

/// Holds the AES key that protects a single notification pair, together
/// with the partner WebID it belongs to.

class NotificationPairKey {
  /// The symmetric key shared between the two PODs in this pair.

  final Key key;

  /// The partner's WebID (i.e. the WebID of the *other* POD in the pair).

  final String partnerWebId;

  const NotificationPairKey({required this.key, required this.partnerWebId});
}

/// Manages the symmetric AES key K_AB associated with a single
/// notification pair, and provides the RSA-encrypted invite payload
/// used to bootstrap a fresh channel.
///
/// Storage:
///   - K_AB is generated by whichever side initiates the channel and
///     persisted in each POD's encryption folder as
///     `notification-<partnerPairId>.json` (encrypted with that POD's
///     master key). A and C therefore use independent keys, satisfying
///     the requirement that distinct pairs remain cryptographically
///     independent.
///
/// Bootstrap:
///   - The initiator drops an `invite-from-<senderPairId>.json` file
///     into the recipient's `notifications/` folder via the container's
///     public Append ACL. The invite carries K_AB encrypted with the
///     recipient's public RSA key (read from
///     `sharing/public-key.ttl`), the sender WebID, and the URL of the
///     sender's outbox file. The recipient's next poll decrypts the
///     invite with their RSA private key, persists K_AB locally, and
///     deletes the consumed invite.

class NotificationPairKeyManager {
  /// POD-relative path of the local key file for the pair whose
  /// partner WebID has the given [pairId].

  static String _localKeyPath(String pairId) =>
      [appDirName, encDir, 'notification-$pairId.json'].join('/');

  /// Filename used for the RSA-encrypted invite that the *sender* drops
  /// into the *recipient's* notifications folder when bootstrapping the
  /// channel. The file lives in the recipient's POD so the path here is
  /// relative and must be combined with the recipient's POD root by the
  /// caller (do not pass it to [getFileUrl] which resolves against the
  /// current user).

  static String inviteFileName(String senderPairId) =>
      'invite-from-$senderPairId.json';

  /// Returns the full URL of the local pair key file for [partnerWebId]
  /// in the *current* user's POD.

  static Future<String> localKeyUrlFor(String partnerWebId) async {
    final pairId = derivePairId(partnerWebId);
    return getFileUrl(_localKeyPath(pairId));
  }

  /// Look up the AES key for the pair with [partnerWebId] in the
  /// current user's encryption folder. Returns `null` when no key file
  /// exists (the pair has never been initialised on this side).
  ///
  /// Throws when the key file exists but cannot be decrypted (typically
  /// because the security key on this device has been rotated and the
  /// stored ciphertext is stale).

  static Future<NotificationPairKey?> loadKey(String partnerWebId) async {
    final url = await localKeyUrlFor(partnerWebId);
    if (await checkResourceStatus(url) != ResourceStatus.exist) return null;

    final raw = utf8.decode(await getResource(url));
    final json = jsonDecode(raw) as Map<String, dynamic>;
    final iv = IV.fromBase64(json['iv'] as String);
    final encKey = json['encKey'] as String;
    final partner = (json['partnerWebId'] as String?) ?? partnerWebId;

    final masterKey = await KeyManager.getMasterKey();
    final keyBase64 = decryptData(encKey, masterKey, iv);
    return NotificationPairKey(
      key: Key.fromBase64(keyBase64),
      partnerWebId: partner,
    );
  }

  /// Save [pairKey] for [partnerWebId] in the current user's encryption
  /// folder, overwriting any previous entry. Overwrite is the desired
  /// behaviour when an invitation re-keys an existing channel.

  static Future<void> saveKey({
    required String partnerWebId,
    required Key pairKey,
  }) async {
    final masterKey = await KeyManager.getMasterKey();
    final iv = genRandIV();
    final encKey = encryptData(pairKey.base64, masterKey, iv);
    final url = await localKeyUrlFor(partnerWebId);
    final body = jsonEncode({
      'iv': iv.base64,
      'encKey': encKey,
      'partnerWebId': partnerWebId,
    });

    await createResource(
      url,
      content: body,
      contentType: ResourceContentType.auto,
    );
  }

  /// Returns the existing key for [partnerWebId], or generates and
  /// stores a new one if no key has been recorded for this pair yet.
  /// The [created] flag tells the caller whether a brand new channel
  /// was bootstrapped (and therefore an invite should be sent to the
  /// partner) or whether an existing key was reused.

  static Future<({NotificationPairKey pair, bool created})> getOrCreateKey(
    String partnerWebId,
  ) async {
    final existing = await loadKey(partnerWebId);
    if (existing != null) return (pair: existing, created: false);

    final newKey = genRandIndividualKey();
    await saveKey(partnerWebId: partnerWebId, pairKey: newKey);

    return (
      pair: NotificationPairKey(key: newKey, partnerWebId: partnerWebId),
      created: true,
    );
  }

  /// Random AES key, fresh per pair.

  static Key genRandIndividualKey() => Key.fromSecureRandom(32);

  /// Build the JSON body of an RSA-encrypted invite addressed to the
  /// partner's POD. The body carries:
  ///  - the sender's WebID (so the recipient knows who is initiating);
  ///  - the URL of the sender's outbox file (so the recipient knows
  ///    where to cross-POD read incoming notifications from);
  ///  - the pair AES key K_AB encrypted with the recipient's public RSA
  ///    key so that only the recipient can recover it.
  ///
  /// The recipient's public key is read live from their
  /// `sharing/public-key.ttl`, mirroring the existing share-by-public-
  /// key flow used elsewhere in the package.

  static Future<String> buildInvitePayload({
    required String senderWebId,
    required String partnerWebId,
    required Key pairKey,
    required String outboxUrl,
  }) async {
    final recipient = RecipientPubKey(recipientWebId: partnerWebId);
    final encKey = await recipient.encryptData(pairKey.base64);

    return jsonEncode({
      'senderWebId': senderWebId,
      'encKey': encKey,
      'outboxUrl': outboxUrl,
      'createdAt': DateTime.now().millisecondsSinceEpoch,
    });
  }

  /// Decrypt an invite [payload] using the current user's private RSA
  /// key and return the recovered pair key alongside the sender
  /// metadata.
  ///
  /// Returns `null` when the payload cannot be decrypted — typically
  /// because the invite was encrypted against an older public key (e.g.
  /// after a re-init). The caller is expected to log and ignore it.

  static Future<({String senderWebId, String outboxUrl, Key key})?>
      decryptInvitePayload(String payload) async {
    try {
      final json = jsonDecode(payload) as Map<String, dynamic>;
      final senderWebId = json['senderWebId'] as String;
      final outboxUrl = json['outboxUrl'] as String;
      final encKey = json['encKey'] as String;

      final privateKey = await KeyManager.getPrivateKey();
      final encrypter = Encrypter(
        RSA(privateKey: RSAKeyParser().parse(privateKey) as RSAPrivateKey),
      );
      final keyBase64 = encrypter.decrypt64(encKey);
      return (
        senderWebId: senderWebId,
        outboxUrl: outboxUrl,
        key: Key.fromBase64(keyBase64),
      );
    } on Object catch (e) {
      debugPrint(
        'NotificationPairKeyManager: failed to decrypt invite payload: $e',
      );
      return null;
    }
  }
}
