/// Shared key management for encrypted resources.
///
/// Copyright (C) 2024, Software Innovation Institute, ANU.
///
/// Licensed under the MIT License (the "License").
///
/// License: https://choosealicense.com/licenses/mit/.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
///
/// Authors: Dawei Chen, Anushka Vidanage

library;

import 'package:flutter/foundation.dart' show debugPrint;

import 'package:encrypter_plus/encrypter_plus.dart';
import 'package:pointycastle/asymmetric/api.dart';
import 'package:rdflib/rdflib.dart' show Namespace;

import 'package:solidpod/src/solid/api/rest_api.dart';
import 'package:solidpod/src/solid/constants/schema.dart' show appsResId;
import 'package:solidpod/src/solid/utils/get_url_helper.dart';
import 'package:solidpod/src/solid/utils/key_helper.dart';
import 'package:solidpod/src/solid/utils/misc.dart';

/// Manages shared encryption keys for resources.

class SharedKeyManager {
  // URL of the file with shared encrypted individual keys.

  static String? _sharedIndKeyUrl;

  // The decrypted shared individual keys.
  // Dictionary key: URL of resource unique ID of the form
  // https://solidcommunity.au/predicates/resourceid#UNIQUE_ID_STR
  // where UNIQUE_ID_STR is generated by `getUniqueIdResUrl()`.

  static Map<String, SharedIndKeyRecord>? _sharedIndKeyMap;

  // For decryption using RSA private key.

  static Encrypter? _rsaEncrypter;

  /// Clear all cached shared keys.

  static void clear() {
    _sharedIndKeyUrl = null;
    _sharedIndKeyMap = null;
    _rsaEncrypter = null;
  }

  /// Load shared (encrypted) individual keys.
  ///
  /// Throws an exception if user is not logged in.

  static Future<void> loadSharedKeys({bool forceReload = false}) async {
    if (_sharedIndKeyMap != null && !forceReload) {
      return;
    }

    final indKeyMap = await readSharedIndKey();

    if (_sharedIndKeyMap == null || _sharedIndKeyMap!.isEmpty) {
      _sharedIndKeyMap = indKeyMap;
    } else {
      final newIdSet = Set<String>.from(indKeyMap.keys);
      final oldIdSet = Set<String>.from(_sharedIndKeyMap!.keys);

      // Add new records.

      final toAdd = newIdSet.difference(oldIdSet);

      if (toAdd.isNotEmpty) {
        _sharedIndKeyMap!.addAll({for (final k in toAdd) k: indKeyMap[k]!});
      }

      // Remove outdated records.

      final toDel = oldIdSet.difference(newIdSet);
      if (toDel.isNotEmpty) {
        _sharedIndKeyMap!.removeWhere((k, v) => toDel.contains(k));
      }
    }
  }

  // Generate the URL with unique ID of shared resource.

  static Future<String> _getResourceIdUrl(String resourceUrl) async {
    final webId = await getWebId();
    assert(webId != null);

    final resourceId = getUniqueIdResUrl(resourceUrl, webId!);
    return getPredicateUrl(resourceId, ns: Namespace(ns: appsResId));
  }

  /// Retrieve the (decrypted) individual key for a shared encrypted resource.
  ///
  /// Return null if the corresponding key does not exist.

  static Future<Key?> getSharedIndividualKey(
    String resourceUrl,
    String privateKey,
  ) async {
    // Check whether _sharedIndKeyMap is empty as when
    // readExternalPod() called on file list concurrently,
    // _sharedIndKeyMap can exist but not yet have the data
    // map when a prior _loadSharedIndKeyFile is not finished

    final uniqueIdUrl = await _getResourceIdUrl(resourceUrl);

    if (_sharedIndKeyMap == null ||
        _sharedIndKeyMap!.isEmpty ||
        !_sharedIndKeyMap!.containsKey(uniqueIdUrl)) {
      await loadSharedKeys(forceReload: true);
    }

    assert(_sharedIndKeyMap != null);

    if (!_sharedIndKeyMap!.containsKey(uniqueIdUrl)) {
      return null;
    }

    final record = _sharedIndKeyMap![uniqueIdUrl];
    assert(record != null);

    if (record!.key == null) {
      _rsaEncrypter ??= Encrypter(
        RSA(
          privateKey: RSAKeyParser().parse(privateKey) as RSAPrivateKey,
        ),
      );

      record.resourcePath = _rsaEncrypter!.decrypt64(record.encResourcePath);
      record.accessList = _rsaEncrypter!.decrypt64(record.encAccessList);
      record.key = Key.fromBase64(_rsaEncrypter!.decrypt64(record.encKey));
      _sharedIndKeyMap![uniqueIdUrl] = record;
    }

    return record.key!;
  }

  /// Remove the (encrypted) shared individual key for file.

  static Future<void> removeSharedIndividualKey(String resourceUrl) async {
    if (_sharedIndKeyMap == null) {
      await loadSharedKeys();
    }
    assert(_sharedIndKeyMap != null);

    final uniqueIdUrl = await _getResourceIdUrl(resourceUrl);

    if (_sharedIndKeyMap!.containsKey(uniqueIdUrl)) {
      final record = _sharedIndKeyMap!.remove(uniqueIdUrl);
      assert(record != null);

      // Delete shared key from shared keys file.

      final query = await getSharedIndKeyDeletionQuery(uniqueIdUrl, record!);
      _sharedIndKeyUrl ??= await getFileUrl(await getSharedKeyFilePath());

      await updateFileByQuery(_sharedIndKeyUrl!, query);

      debugPrint('Deleted $record');
    } else {
      debugPrint(
        'Shared individual key for "$resourceUrl" does not exist, do nothing.',
      );
    }
  }
}
